safe:         true
port:         4000
url:          http://localhost:4000
host_name:    adamralph.com

source:       .
destination:  ./_site
plugins_dir:  ./_plugins

plugins:
  - jemoji
  - jekyll-feed

future:       true
lsi:          false
highlighter:  rouge
permalink:    pretty

kramdown:
  auto_ids:       true,
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false
