plugins:
  - jemoji
  - jekyll-feed
  - jekyll-redirect-from

title: Adam Ralph
description: Software, tea, and snowboarding
url: https://adamralph.com
author: Adam Ralph
excerpt_separator: <!--excerpt-->

permalink:    pretty
